name: Auto Tweet Using AI

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest

    # add this line so environment secrets are injected
    environment: right

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Twitter bot
        run: npm start
